### ISSUE TITLE
Minimal translations corrections 

### ISSUE THREAD

**Issue by rockman6554** [leandrogavidia/rick-and-morty-character-factory#1]
On the dialog box 'View all history' the button "Closed" must to be "Close"

Great work Leandro...

**Comment by leandrogavidia** [comment]
Hi rockman6554, thank you very much for your contribution.

You are right, and I just changed it.

Thank you again.

**Comment by leandrogavidia** [comment]
> On the dialog box 'View all history' the button "Closed" must to be "Close"
> 
> Great work Leandro...



> On the dialog box 'View all history' the button "Closed" must to be "Close"
> 
> Great work Leandro...

Hi rockman6554, thank you very much for your contribution.

You are right, and I just changed it.

Thank you again.

**Comment by leandrogavidia** [comment]
> On the dialog box 'View all history' the button "Closed" must to be "Close"
> 
> Great work Leandro...

Hi rockman6554, thank you very much for your contribution.

You are right, and I just changed it.

Thank you again.
